### ISSUE TITLE
Check worker health for kubernetes

### ISSUE THREAD

**Issue by bat79a** [rq/django-rq#363]
Hi All.

Can I check with a http request or tcp or command if the worker is up in my pod ?
I need this health check for kubernetes.

Thx a lot.

**Comment by bat79a** [comment]
Hi.

I have found a solution by adding a probe.

- add a script inside the container that return a 0 value if my python pid is up (python rqworker)

- add in the kubernetes yml description a command who start the script for the livenessProbe and the readinessProbe.

exemple :
```
        resources:
          requests:
            memory: "200Mi"
        readinessProbe:
          exec:
            command:
            - "/srv/probe.sh"  # path to my script file
        livenessProbe:
          exec:
            command:
            - "/srv/probe.sh"
          initialDelaySeconds: 15
          periodSeconds: 20
```

If someone find a better solution don't hesitate ;p

Thx.
